meta(charset:"utf-8") newLine()
meta(name:"viewport", content:"width=device-width, initial-scale=1.0") newLine()
title("${config.blog_title}") newLine()

link(rel:"shortcut", href:"${config.site_contextPath}icons/myJ.png") newLine()
link(rel:"shortcut icon", href:"${config.site_contextPath}icons/myJ.png") newLine()
meta(property:"og:locale", content:"en_US") newLine()
meta(property:"og:type", content:"website") newLine()
meta(property:"og:title", content:"${config.blog_title} - ${config.blog_subtitle}") newLine()
meta(property:"og:description", content:"${config.blog_description}") newLine()
meta(property:"og:url", content:"${config.site_contextPath}") newLine()
meta(property:"og:site_name", content:"${config.blog_title}") newLine()
meta(name:"twitter:card", content:"summary") newLine()
meta(name:"twitter:description", content:"${config.blog_description}") newLine()
meta(name:"twitter:title", content:"${config.blog_title} - ${config.blog_subtitle}") newLine()
link(rel:"stylesheet", href:"${config.site_contextPath}css/asciidoctor.css") newLine()
link(rel:"stylesheet", href:"${config.site_contextPath}css/foundation.css") newLine()
link(rel:"stylesheet", href:"${config.site_contextPath}css/social_foundicons.css") newLine()
link(rel:"stylesheet", href:"${config.site_contextPath}css/prettify.css") newLine()
link(rel:"stylesheet", href:"${config.site_contextPath}css/desert.css") newLine()
link(rel:"stylesheet", href:"${config.site_contextPath}css/app.css") newLine()
newLine()
script(src:"${config.site_contextPath}js/vendor/modernizr.js"){} newLine()
script(src:"${config.site_contextPath}js/app.js"){} newLine()